Repository UMC-ZIC/ZIC, pull requests merged in 2025-02, with the labels that each got.

#61 chore#58-AWS-CI-CD
  .github/workflows/deploy.yml
  src/main/resources/application.yml
Labels: chore, rename

#66 feature: CROS 설정
  src/main/java/com/umc7/ZIC/config/WebMvcConfig.java
Labels: :sparkles: feature

#71 CICD: Main 브랜치로 병합
  src/main/java/com/umc7/ZIC/practiceRoom/controller/PracticeRoomDetailController.java
  src/main/java/com/umc7/ZIC/practiceRoom/domain/PracticeRoom.java
  src/main/java/com/umc7/ZIC/practiceRoom/domain/PracticeRoomDetail.java
  src/main/java/com/umc7/ZIC/practiceRoom/dto/AvailableTimeSlot.java
  src/main/java/com/umc7/ZIC/practiceRoom/dto/PracticeRoomDetailResponseDto.java
  src/main/java/com/umc7/ZIC/practiceRoom/dto/PracticeRoomRequestDto.java
  src/main/java/com/umc7/ZIC/practiceRoom/dto/PracticeRoomResponseDto.java
  src/main/java/com/umc7/ZIC/practiceRoom/service/PracticeRoomDetailService.java
  src/main/java/com/umc7/ZIC/practiceRoom/service/PracticeRoomDetailServiceImpl.java
  src/main/java/com/umc7/ZIC/practiceRoom/validation/validator/PracticeRoomDetailStatusCheckValidator.java
Labels: CI/CD

#73 remove: 위도 경도 notnull 제거
  src/main/java/com/umc7/ZIC/practiceRoom/dto/PracticeRoomRequestDto.java
  src/main/java/com/umc7/ZIC/user/service/UserServiceImpl.java
Labels: code remove

#74 feature: swagger api 설명 추가
  src/main/java/com/umc7/ZIC/user/controller/OwnerController.java
  src/main/java/com/umc7/ZIC/user/controller/UserController.java
Labels: :sparkles: feature

#75 CICD: Main 브랜치로 병합
  src/main/java/com/umc7/ZIC/practiceRoom/dto/PracticeRoomRequestDto.java
  src/main/java/com/umc7/ZIC/user/controller/OwnerController.java
  src/main/java/com/umc7/ZIC/user/controller/UserController.java
  src/main/java/com/umc7/ZIC/user/service/UserServiceImpl.java
Labels: :rocket: CI/CD

#80 fix: refresh 토큰 -> access 토큰 수정
  src/main/java/com/umc7/ZIC/common/controller/TestLoginController.java
Labels: :lady_beetle: fix

#84 feature: jwt토큰 유저 이름 추가
  src/main/java/com/umc7/ZIC/common/controller/TestLoginController.java
  src/main/java/com/umc7/ZIC/security/CustomOAuth2UserService.java
  src/main/java/com/umc7/ZIC/security/JwtTokenProvider.java
  src/main/java/com/umc7/ZIC/security/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/umc7/ZIC/user/service/UserServiceImpl.java
Labels: :sparkles: feature

#85 CICD: Main 브랜치로 병합
  src/main/java/com/umc7/ZIC/common/controller/TestLoginController.java
  src/main/java/com/umc7/ZIC/practiceRoom/controller/PracticeRoomController.java
  src/main/java/com/umc7/ZIC/practiceRoom/controller/PracticeRoomDetailController.java
  src/main/java/com/umc7/ZIC/practiceRoom/dto/PageResponseDto.java
  src/main/java/com/umc7/ZIC/practiceRoom/service/PracticeRoomDetailService.java
  src/main/java/com/umc7/ZIC/practiceRoom/service/PracticeRoomDetailServiceImpl.java
  src/main/java/com/umc7/ZIC/practiceRoom/service/PracticeRoomService.java
  src/main/java/com/umc7/ZIC/practiceRoom/service/PracticeRoomServiceImpl.java
  src/main/java/com/umc7/ZIC/security/CustomOAuth2UserService.java
  src/main/java/com/umc7/ZIC/security/JwtTokenProvider.java
  src/main/java/com/umc7/ZIC/security/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/umc7/ZIC/user/service/UserServiceImpl.java
Labels: :rocket: CI/CD

#86 feature: 카카오 프로필 사진 저장
  src/main/java/com/umc7/ZIC/security/CustomOAuth2UserService.java
  src/main/java/com/umc7/ZIC/security/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/umc7/ZIC/user/domain/User.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#88 feature: 카카오 로그인 성공 핸들러 수정
  src/main/java/com/umc7/ZIC/common/controller/KakaoLoginPageController.java
  src/main/java/com/umc7/ZIC/config/WebMvcConfig.java
  src/main/java/com/umc7/ZIC/security/OAuith2AuthenticationFailureHandler.java
  src/main/java/com/umc7/ZIC/security/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/umc7/ZIC/security/SecurityConfig.java
  src/main/java/com/umc7/ZIC/user/controller/KakaoLoginPageController.java
  src/main/java/com/umc7/ZIC/user/controller/UserController.java
  src/main/java/com/umc7/ZIC/user/converter/UserConverter.java
  src/main/java/com/umc7/ZIC/user/dto/KakaoTokenResponseDto.java
  src/main/java/com/umc7/ZIC/user/dto/KakaoUserInfoResponseDto.java
  src/main/java/com/umc7/ZIC/user/service/KakaoService.java
  src/main/java/com/umc7/ZIC/user/service/UserService.java
  src/main/java/com/umc7/ZIC/user/service/UserServiceImpl.java
  src/main/resources/templates/login.html
Labels: :sparkles: feature

#90 bugfix: merge 이후 수정 안 된 부분 수정
  src/main/java/com/umc7/ZIC/security/JwtTokenProvider.java
  src/main/java/com/umc7/ZIC/user/service/UserServiceImpl.java
  src/main/resources/application.yml
Labels: :lady_beetle: fix

#91 CICD: Main 브랜치로 병합
  src/main/java/com/umc7/ZIC/common/controller/KakaoLoginPageController.java
  src/main/java/com/umc7/ZIC/config/WebMvcConfig.java
  src/main/java/com/umc7/ZIC/security/CustomOAuth2UserService.java
  src/main/java/com/umc7/ZIC/security/JwtTokenProvider.java
  src/main/java/com/umc7/ZIC/security/OAuith2AuthenticationFailureHandler.java
  src/main/java/com/umc7/ZIC/security/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/umc7/ZIC/security/SecurityConfig.java
  src/main/java/com/umc7/ZIC/user/controller/KakaoLoginPageController.java
  src/main/java/com/umc7/ZIC/user/controller/UserController.java
  src/main/java/com/umc7/ZIC/user/converter/UserConverter.java
  src/main/java/com/umc7/ZIC/user/domain/User.java
  src/main/java/com/umc7/ZIC/user/dto/KakaoTokenResponseDto.java
  src/main/java/com/umc7/ZIC/user/dto/KakaoUserInfoResponseDto.java
  src/main/java/com/umc7/ZIC/user/service/KakaoService.java
  src/main/java/com/umc7/ZIC/user/service/UserService.java
  src/main/java/com/umc7/ZIC/user/service/UserServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/templates/login.html
Labels: :rocket: CI/CD

#92 feature#87 대여자 예약 조회 기능 및 이용상태 전환 api 추가
  src/main/java/com/umc7/ZIC/practiceRoom/controller/PracticeRoomDetailController.java
  src/main/java/com/umc7/ZIC/practiceRoom/domain/PracticeRoom.java
  src/main/java/com/umc7/ZIC/practiceRoom/domain/PracticeRoomDetail.java
  src/main/java/com/umc7/ZIC/practiceRoom/dto/PracticeRoomDetailRequestDto.java
  src/main/java/com/umc7/ZIC/practiceRoom/dto/PracticeRoomRequestDto.java
  src/main/java/com/umc7/ZIC/practiceRoom/service/PracticeRoomDetailService.java
  src/main/java/com/umc7/ZIC/practiceRoom/service/PracticeRoomDetailServiceImpl.java
  src/main/java/com/umc7/ZIC/reservation/controller/ReservationRestController.java
  src/main/java/com/umc7/ZIC/reservation/converter/ReservationConverter.java
  src/main/java/com/umc7/ZIC/reservation/dto/ReservationResponseDTO.java
  src/main/java/com/umc7/ZIC/reservation/repository/ReservationRepository.java
  src/main/java/com/umc7/ZIC/reservation/service/ReservationQueryService.java
  src/main/java/com/umc7/ZIC/reservation/service/ReservationQueryServiceImpl.java
Labels: :sparkles: feature

#95 bugfix: OneToOne 을 ManyToOne으로 설정
  src/main/java/com/umc7/ZIC/common/domain/Region.java
  src/main/java/com/umc7/ZIC/user/domain/User.java
Labels: :lady_beetle: fix

#97 bugfix: practiceRoom_instrument DB 저장
  src/main/java/com/umc7/ZIC/user/service/UserServiceImpl.java
Labels: :lady_beetle: fix

#98 bugfix: practiceRoom_instrument DB 저장
  src/main/java/com/umc7/ZIC/practiceRoom/converter/PracticeRoomInstrumentConverter.java
  src/main/java/com/umc7/ZIC/practiceRoom/repository/PracticeRoomInstrumentRepository.java
Labels: :lady_beetle: fix

#99 bugfix: 연습실 이름을 비즈니스 이름으로 수정
  src/main/java/com/umc7/ZIC/user/service/UserServiceImpl.java
Labels: :lady_beetle: fix

#100 feature: 이용자 마이페이지 구현, reafactor: 일부 메서드 대문자로 수정
  src/main/java/com/umc7/ZIC/reservation/repository/ReservationRepositoryCustom.java
  src/main/java/com/umc7/ZIC/reservation/repository/ReservationRepositoryImpl.java
  src/main/java/com/umc7/ZIC/user/controller/KakaoLoginPageController.java
  src/main/java/com/umc7/ZIC/user/controller/OwnerController.java
  src/main/java/com/umc7/ZIC/user/controller/UserController.java
  src/main/java/com/umc7/ZIC/user/converter/UserConverter.java
  src/main/java/com/umc7/ZIC/user/dto/UserResponseDto.java
  src/main/java/com/umc7/ZIC/user/repository/UserRepositoryCustom.java
  src/main/java/com/umc7/ZIC/user/repository/UserRepositoryImpl.java
  src/main/java/com/umc7/ZIC/user/service/UserService.java
  src/main/java/com/umc7/ZIC/user/service/UserServiceImpl.java
Labels: :hammer: refactor, :sparkles: feature

#101 Bugfix: 대여자 가입시 연습실 id도 response. refactor: 메서드 이름 변경
  src/main/java/com/umc7/ZIC/user/controller/OwnerController.java
  src/main/java/com/umc7/ZIC/user/controller/UserController.java
  src/main/java/com/umc7/ZIC/user/converter/UserConverter.java
  src/main/java/com/umc7/ZIC/user/dto/UserResponseDto.java
  src/main/java/com/umc7/ZIC/user/service/UserService.java
  src/main/java/com/umc7/ZIC/user/service/UserServiceImpl.java
Labels: :lady_beetle: fix, :hammer: refactor

#102 CICD: Main 브랜치로 병합
  src/main/java/com/umc7/ZIC/common/domain/Region.java
  src/main/java/com/umc7/ZIC/practiceRoom/controller/PracticeRoomDetailController.java
  src/main/java/com/umc7/ZIC/practiceRoom/converter/PracticeRoomInstrumentConverter.java
  src/main/java/com/umc7/ZIC/practiceRoom/domain/PracticeRoom.java
  src/main/java/com/umc7/ZIC/practiceRoom/domain/PracticeRoomDetail.java
  src/main/java/com/umc7/ZIC/practiceRoom/dto/PracticeRoomDetailRequestDto.java
  src/main/java/com/umc7/ZIC/practiceRoom/dto/PracticeRoomRequestDto.java
  src/main/java/com/umc7/ZIC/practiceRoom/repository/PracticeRoomInstrumentRepository.java
  src/main/java/com/umc7/ZIC/practiceRoom/service/PracticeRoomDetailService.java
  src/main/java/com/umc7/ZIC/practiceRoom/service/PracticeRoomDetailServiceImpl.java
  src/main/java/com/umc7/ZIC/reservation/controller/ReservationRestController.java
  src/main/java/com/umc7/ZIC/reservation/converter/ReservationConverter.java
  src/main/java/com/umc7/ZIC/reservation/dto/ReservationResponseDTO.java
  src/main/java/com/umc7/ZIC/reservation/repository/ReservationRepository.java
  src/main/java/com/umc7/ZIC/reservation/repository/ReservationRepositoryCustom.java
  src/main/java/com/umc7/ZIC/reservation/repository/ReservationRepositoryImpl.java
  src/main/java/com/umc7/ZIC/reservation/service/ReservationQueryService.java
  src/main/java/com/umc7/ZIC/reservation/service/ReservationQueryServiceImpl.java
  src/main/java/com/umc7/ZIC/user/controller/KakaoLoginPageController.java
  src/main/java/com/umc7/ZIC/user/controller/OwnerController.java
  src/main/java/com/umc7/ZIC/user/controller/UserController.java
  src/main/java/com/umc7/ZIC/user/converter/UserConverter.java
  src/main/java/com/umc7/ZIC/user/domain/User.java
  src/main/java/com/umc7/ZIC/user/dto/UserResponseDto.java
  src/main/java/com/umc7/ZIC/user/repository/UserRepositoryCustom.java
  src/main/java/com/umc7/ZIC/user/repository/UserRepositoryImpl.java
  src/main/java/com/umc7/ZIC/user/service/UserService.java
  src/main/java/com/umc7/ZIC/user/service/UserServiceImpl.java
Labels: :rocket: CI/CD

#104 feature: redis 구현
  build.gradle
  src/main/java/com/umc7/ZIC/common/util/RedisUtil.java
  src/main/java/com/umc7/ZIC/config/RedisConfig.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#105 feature: cors 시큐리티에 적용설정 및 preflight 요청 처리
  src/main/java/com/umc7/ZIC/security/SecurityConfig.java
Labels: :sparkles: feature

#110 feature: jwt토큰 시간 변경
  src/main/java/com/umc7/ZIC/security/JwtTokenProvider.java
Labels: :sparkles: feature

#111 rename: OAuth 관련 클래스 위치 변경
  src/main/java/com/umc7/ZIC/security/OAuth/CustomOAuth2User.java
  src/main/java/com/umc7/ZIC/security/OAuth/CustomOAuth2UserService.java
  src/main/java/com/umc7/ZIC/security/OAuth/OAuith2AuthenticationFailureHandler.java
  src/main/java/com/umc7/ZIC/security/OAuth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/umc7/ZIC/security/SecurityConfig.java
Labels: :truck: rename

#112 feature: cors 허용 도메인 정리
  src/main/java/com/umc7/ZIC/security/SecurityConfig.java
Labels: :sparkles: feature

#113 CI/CD
  build.gradle
  src/main/java/com/umc7/ZIC/common/util/RedisUtil.java
  src/main/java/com/umc7/ZIC/config/RedisConfig.java
  src/main/java/com/umc7/ZIC/security/JwtTokenProvider.java
  src/main/java/com/umc7/ZIC/security/OAuth/CustomOAuth2User.java
  src/main/java/com/umc7/ZIC/security/OAuth/CustomOAuth2UserService.java
  src/main/java/com/umc7/ZIC/security/OAuth/OAuith2AuthenticationFailureHandler.java
  src/main/java/com/umc7/ZIC/security/OAuth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/umc7/ZIC/security/SecurityConfig.java
  src/main/resources/application.yml
Labels: :rocket: CI/CD

#115 feature: 개발 테스트 로그인 성공 url 변경
  src/main/java/com/umc7/ZIC/security/OAuth/OAuth2AuthenticationSuccessHandler.java
Labels: :sparkles: feature

#116 CICD: Main 브랜치로 병합
  src/main/java/com/umc7/ZIC/security/OAuth/OAuth2AuthenticationSuccessHandler.java
Labels: :rocket: CI/CD

#117 feature: 마이페이지 스웨거 설명 추가
  src/main/java/com/umc7/ZIC/user/controller/UserController.java
Labels: :sparkles: feature

#119 CI/CD
  src/main/java/com/umc7/ZIC/common/controller/TestLoginController.java
  src/main/java/com/umc7/ZIC/reservation/converter/KakaoPayConverter.java
  src/main/java/com/umc7/ZIC/user/controller/UserController.java
Labels: :rotating_light: test, :sparkles: feature, :rocket: CI/CD

#133 feature: 연습실 기본 이미지 적용
  src/main/java/com/umc7/ZIC/user/service/UserServiceImpl.java
Labels: :sparkles: feature

#135 fix: 악기 한글 오타 수정
  src/main/java/com/umc7/ZIC/common/domain/enums/InstrumentType.java
Labels: :lady_beetle: fix

#137 feature#114 practice room api mod
  src/main/java/com/umc7/ZIC/common/domain/enums/RegionType.java
  src/main/java/com/umc7/ZIC/common/service/RegionService.java
  src/main/java/com/umc7/ZIC/common/service/RegionServiceImpl.java
  src/main/java/com/umc7/ZIC/practiceRoom/controller/PracticeRoomController.java
  src/main/java/com/umc7/ZIC/practiceRoom/controller/PracticeRoomDetailController.java
  src/main/java/com/umc7/ZIC/practiceRoom/domain/PracticeRoom.java
  src/main/java/com/umc7/ZIC/practiceRoom/dto/PageRequestDto.java
  src/main/java/com/umc7/ZIC/practiceRoom/dto/PracticeRoomDetailResponseDto.java
  src/main/java/com/umc7/ZIC/practiceRoom/dto/PracticeRoomResponseDto.java
  src/main/java/com/umc7/ZIC/practiceRoom/repository/PracticeRoomDetailRepository.java
  src/main/java/com/umc7/ZIC/practiceRoom/repository/PracticeRoomRepository.java
  src/main/java/com/umc7/ZIC/practiceRoom/service/PracticeRoomDetailService.java
  src/main/java/com/umc7/ZIC/practiceRoom/service/PracticeRoomDetailServiceImpl.java
  src/main/java/com/umc7/ZIC/practiceRoom/service/PracticeRoomService.java
  src/main/java/com/umc7/ZIC/practiceRoom/service/PracticeRoomServiceImpl.java
Labels: :lady_beetle: fix, :hammer: refactor, :sparkles: feature

#138 Bugfix: 대여자 악기 선택 null 처리 및 지역 처리 수정
  src/main/java/com/umc7/ZIC/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc7/ZIC/common/util/InstrumentUtil.java
  src/main/java/com/umc7/ZIC/security/JwtFilter.java
  src/main/java/com/umc7/ZIC/user/service/UserServiceImpl.java
Labels: :lady_beetle: fix

#142 feature: 예약 요청 api validation 수정
  src/main/java/com/umc7/ZIC/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc7/ZIC/reservation/controller/ReservationRestController.java
  src/main/java/com/umc7/ZIC/reservation/repository/ReservationRepositoryCustom.java
  src/main/java/com/umc7/ZIC/reservation/repository/ReservationRepositoryImpl.java
  src/main/java/com/umc7/ZIC/reservation/service/ReservationQueryService.java
  src/main/java/com/umc7/ZIC/reservation/service/ReservationQueryServiceImpl.java
  src/main/java/com/umc7/ZIC/reservation/validation/validator/ReservationTimeOverlapCheckValidator.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#143 Feature#140 practice room get list filter add
  src/main/java/com/umc7/ZIC/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc7/ZIC/common/domain/enums/InstrumentType.java
  src/main/java/com/umc7/ZIC/common/service/InstrumentService.java
  src/main/java/com/umc7/ZIC/common/service/InstrumentServiceImpl.java
  src/main/java/com/umc7/ZIC/common/service/RegionServiceImpl.java
  src/main/java/com/umc7/ZIC/practiceRoom/controller/PracticeRoomController.java
  src/main/java/com/umc7/ZIC/practiceRoom/domain/PracticeRoom.java
  src/main/java/com/umc7/ZIC/practiceRoom/dto/PageRequestDto.java
  src/main/java/com/umc7/ZIC/practiceRoom/dto/PracticeRoomResponseDto.java
  src/main/java/com/umc7/ZIC/practiceRoom/repository/PracticeRoomRepository.java
  src/main/java/com/umc7/ZIC/practiceRoom/repository/PracticeRoomRepositoryCustom.java
  src/main/java/com/umc7/ZIC/practiceRoom/repository/PracticeRoomRepositoryImpl.java
  src/main/java/com/umc7/ZIC/practiceRoom/service/PracticeRoomService.java
  src/main/java/com/umc7/ZIC/practiceRoom/service/PracticeRoomServiceImpl.java
Labels: :sparkles: feature

#144 chore: 연습실 등록 API 비활성화
  src/main/java/com/umc7/ZIC/practiceRoom/controller/PracticeRoomController.java
Labels: :bulb: chore

#146 fix: 예약 성공한 것만 select 되게 변경
  src/main/java/com/umc7/ZIC/reservation/repository/ReservationRepositoryImpl.java
Labels: :lady_beetle: fix

#147 feature: 운영시간 수정
  src/main/java/com/umc7/ZIC/practiceRoom/service/PracticeRoomDetailServiceImpl.java
Labels: :sparkles: feature

#148 fix: 모든 내부방이 이용불가여도 연습실은 조회 되도록 설정
  src/main/java/com/umc7/ZIC/practiceRoom/repository/PracticeRoomRepositoryImpl.java
Labels: :lady_beetle: fix
