Repository UMC-ZIC/ZIC, pull requests merged in 2025-01, with the labels that each got.

#1 main#1: init setting
  .github/ISSUE_TEMPLATE/이슈-생성-템플릿.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  build.gradle
  src/main/java/com/umc7/ZIC/ZicApplication.java
  src/main/java/com/umc7/ZIC/apiPayload/code/BaseCode.java
  src/main/java/com/umc7/ZIC/apiPayload/code/BaseErrorCode.java
  src/main/java/com/umc7/ZIC/apiPayload/code/ErrorReasonDTO.java
  src/main/java/com/umc7/ZIC/apiPayload/code/ReasonDTO.java
  src/main/java/com/umc7/ZIC/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc7/ZIC/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/umc7/ZIC/apiPayload/exception/ApiResponse.java
  src/main/java/com/umc7/ZIC/apiPayload/exception/handler/ExceptionAdvice.java
  src/main/java/com/umc7/ZIC/config/SwaggerConfig.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: :page_facing_up: docs, chore, :sparkles: feature

#9 bugfix: entity mappedBy 수정
  src/main/java/com/umc7/ZIC/common/domain/Instrument.java
Labels: :lady_beetle: fix

#11 refactor: Region 엔티티 클래스 위치 수정 및 enum 값 대문자로 변경
  src/main/java/com/umc7/ZIC/common/domain/Region.java
  src/main/java/com/umc7/ZIC/common/domain/enums/InstrumentType.java
  src/main/java/com/umc7/ZIC/common/domain/enums/RegionType.java
  src/main/java/com/umc7/ZIC/user/domain/User.java
Labels: :hammer: refactor

#12 Feature: practiceRoom 도메인 관련 엔티티 추가
  src/main/java/com/umc7/ZIC/instrument/domain/Instrument.java
  src/main/java/com/umc7/ZIC/practiceRoom/domain/PracticeRoom.java
  src/main/java/com/umc7/ZIC/practiceRoom/domain/PracticeRoomDetail.java
  src/main/java/com/umc7/ZIC/practiceRoom/domain/PracticeRoomInstrument.java
  src/main/java/com/umc7/ZIC/practiceRoom/domain/PracticeRoomLike.java
Labels: :sparkles: feature

#18 bugfix: record 변경에 따른 getter 메서드를 record 형식으로 변경
  src/main/java/com/umc7/ZIC/apiPayload/exception/ApiResponse.java
  src/main/java/com/umc7/ZIC/apiPayload/exception/handler/ExceptionAdvice.java
Labels: :lady_beetle: fix

#20 HOTFIX: gradle swagger 2.6.0 버전 동작 오류
  build.gradle
Labels: HOTFIX

#21 feature: 연습실 관련 레포지터리 구현
  src/main/java/com/umc7/ZIC/common/domain/Region.java
  src/main/java/com/umc7/ZIC/practiceRoom/domain/PracticeRoomDetail.java
  src/main/java/com/umc7/ZIC/practiceRoom/repository/PracticeRoomDetailRepository.java
  src/main/java/com/umc7/ZIC/practiceRoom/repository/PracticeRoomLikeRepository.java
  src/main/java/com/umc7/ZIC/practiceRoom/repository/PracticeRoomRepository.java
  src/main/java/com/umc7/ZIC/practiceRoom/repository/temp/OwnerRepository.java
  src/main/java/com/umc7/ZIC/practiceRoom/repository/temp/RegionRepository.java
  src/main/java/com/umc7/ZIC/practiceRoom/repository/temp/UserRepository.java
  src/main/java/com/umc7/ZIC/user/domain/User.java
  src/test/java/com/umc7/ZIC/practiceRoom/repository/PracticeRoomDetailRepositoryTest.java
  src/test/java/com/umc7/ZIC/practiceRoom/repository/PracticeRoomLikeRepositoryTest.java
  src/test/java/com/umc7/ZIC/practiceRoom/repository/PracticeRoomRepositoryTest.java
Labels: :sparkles: feature

#23 refactor: user owner entity 통합 및 role로 구분
  src/main/java/com/umc7/ZIC/owner/domain/Owner.java
  src/main/java/com/umc7/ZIC/user/domain/User.java
Labels: :hammer: refactor

#24 refactor: enum userType 추가
  src/main/java/com/umc7/ZIC/user/domain/enums/RoleType.java
Labels: :hammer: refactor

#25 feature: user-owner 통합에 따른 entity 수정
  src/main/java/com/umc7/ZIC/practiceRoom/domain/PracticeRoom.java
  src/main/java/com/umc7/ZIC/user/domain/UserInstrument.java
Labels: :sparkles: feature

#26 Feature#14 oauth2, 카카오 로그인, jwt 토큰, security 구현
  build.gradle
  src/main/java/com/umc7/ZIC/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc7/ZIC/apiPayload/exception/handler/RegionHandler.java
  src/main/java/com/umc7/ZIC/apiPayload/exception/handler/UserHandler.java
  src/main/java/com/umc7/ZIC/common/controller/KakaoLoginPageController.java
  src/main/java/com/umc7/ZIC/common/domain/Instrument.java
  src/main/java/com/umc7/ZIC/common/repository/InstrumentRepository.java
  src/main/java/com/umc7/ZIC/common/repository/RegionRepository.java
  src/main/java/com/umc7/ZIC/common/util/InstrumentUtil.java
  src/main/java/com/umc7/ZIC/common/util/RegionUtil.java
  src/main/java/com/umc7/ZIC/config/QueryDSLConfig.java
  src/main/java/com/umc7/ZIC/practiceRoom/repository/temp/OwnerRepository.java
  src/main/java/com/umc7/ZIC/practiceRoom/repository/temp/RegionRepository.java
  src/main/java/com/umc7/ZIC/practiceRoom/repository/temp/UserRepository.java
  src/main/java/com/umc7/ZIC/security/CustomOAuth2User.java
  src/main/java/com/umc7/ZIC/security/CustomOAuth2UserService.java
  src/main/java/com/umc7/ZIC/security/CustomUserDetail.java
  src/main/java/com/umc7/ZIC/security/CustomUserDetailsService.java
  src/main/java/com/umc7/ZIC/security/JwtFilter.java
  src/main/java/com/umc7/ZIC/security/JwtTokenProvider.java
  src/main/java/com/umc7/ZIC/security/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/umc7/ZIC/security/SecurityConfig.java
  src/main/java/com/umc7/ZIC/user/controller/UserController.java
  src/main/java/com/umc7/ZIC/user/converter/UserConverter.java
  src/main/java/com/umc7/ZIC/user/converter/UserInstrumentConverter.java
  src/main/java/com/umc7/ZIC/user/dto/UserRequestDto.java
  src/main/java/com/umc7/ZIC/user/dto/UserResponseDto.java
  src/main/java/com/umc7/ZIC/user/repository/UserInstrumentRepository.java
  src/main/java/com/umc7/ZIC/user/repository/UserRepository.java
  src/main/java/com/umc7/ZIC/user/repository/UserRepositoryImpl.java
  src/main/java/com/umc7/ZIC/user/service/UserService.java
  src/main/java/com/umc7/ZIC/user/service/UserServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/templates/home.html
  src/main/resources/templates/login.html
  src/main/resources/templates/static/kakao_login_medium_narrow.png
  src/main/resources/templates/success.html
Labels: :hammer: refactor, remove, :sparkles: feature

#28 feature: repository 커스텀 인터페이스 추가
  src/main/java/com/umc7/ZIC/user/repository/UserRepositoryCustom.java
Labels: :sparkles: feature

#29 bugfix: 카카오 scope 설정 이메일 동의 해결
  src/main/resources/application.yml
Labels: :lady_beetle: fix

#31 bugfix: csrf 비활성화
  src/main/java/com/umc7/ZIC/security/SecurityConfig.java
Labels: :lady_beetle: fix

#32 feature: 연습실 결제 및 예약 내역 조회 API 구현
  src/main/java/com/umc7/ZIC/common/controller/ReservationPageController.java
  src/main/java/com/umc7/ZIC/reservation/controller/ReservationRestController.java
  src/main/java/com/umc7/ZIC/reservation/converter/KakaoPayConverter.java
  src/main/java/com/umc7/ZIC/reservation/converter/ReservationConverter.java
  src/main/java/com/umc7/ZIC/reservation/domain/Reservation.java
  src/main/java/com/umc7/ZIC/reservation/domain/ReservationDetail.java
  src/main/java/com/umc7/ZIC/reservation/dto/PaymentRequestDTO.java
  src/main/java/com/umc7/ZIC/reservation/dto/PaymentResponseDTO.java
  src/main/java/com/umc7/ZIC/reservation/dto/ReservationRequestDTO.java
  src/main/java/com/umc7/ZIC/reservation/dto/ReservationResponseDTO.java
  src/main/java/com/umc7/ZIC/reservation/repository/ReservationDetailRepository.java
  src/main/java/com/umc7/ZIC/reservation/repository/ReservationRepository.java
  src/main/java/com/umc7/ZIC/reservation/service/KakaoPayService.java
  src/main/java/com/umc7/ZIC/reservation/service/KakaoPayServiceImpl.java
  src/main/java/com/umc7/ZIC/reservation/service/ReservationCommandService.java
  src/main/java/com/umc7/ZIC/reservation/service/ReservationCommandServiceImpl.java
  src/main/java/com/umc7/ZIC/reservation/service/ReservationQueryService.java
  src/main/java/com/umc7/ZIC/reservation/service/ReservationQueryServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/templates/KakaoReady.html
Labels: :hammer: refactor, rename, :sparkles: feature

#35 feature#27 연습실, 연습실 내부방 CRUD
  build.gradle
  src/main/java/com/umc7/ZIC/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc7/ZIC/apiPayload/exception/handler/PracticeRoomDetailHandler.java
  src/main/java/com/umc7/ZIC/apiPayload/exception/handler/PracticeRoomHandler.java
  src/main/java/com/umc7/ZIC/practiceRoom/controller/PracticeRoomController.java
  src/main/java/com/umc7/ZIC/practiceRoom/controller/PracticeRoomDetailController.java
  src/main/java/com/umc7/ZIC/practiceRoom/domain/PracticeRoom.java
  src/main/java/com/umc7/ZIC/practiceRoom/domain/PracticeRoomDetail.java
  src/main/java/com/umc7/ZIC/practiceRoom/domain/enums/RoomStatus.java
  src/main/java/com/umc7/ZIC/practiceRoom/dto/PageRequestDto.java
  src/main/java/com/umc7/ZIC/practiceRoom/dto/PageResponseDto.java
  src/main/java/com/umc7/ZIC/practiceRoom/dto/PracticeRoomDetailRequestDto.java
  src/main/java/com/umc7/ZIC/practiceRoom/dto/PracticeRoomDetailResponseDto.java
  src/main/java/com/umc7/ZIC/practiceRoom/dto/PracticeRoomRequestDto.java
  src/main/java/com/umc7/ZIC/practiceRoom/dto/PracticeRoomResponseDto.java
  src/main/java/com/umc7/ZIC/practiceRoom/repository/PracticeRoomDetailRepository.java
  src/main/java/com/umc7/ZIC/practiceRoom/service/PracticeRoomDetailService.java
  src/main/java/com/umc7/ZIC/practiceRoom/service/PracticeRoomDetailServiceImpl.java
  src/main/java/com/umc7/ZIC/practiceRoom/service/PracticeRoomService.java
  src/main/java/com/umc7/ZIC/practiceRoom/service/PracticeRoomServiceImpl.java
  src/main/java/com/umc7/ZIC/user/domain/User.java
  src/main/resources/application.yml
  src/test/java/com/umc7/ZIC/practiceRoom/repository/PracticeRoomDetailRepositoryTest.java
  src/test/java/com/umc7/ZIC/practiceRoom/repository/PracticeRoomLikeRepositoryTest.java
  src/test/java/com/umc7/ZIC/practiceRoom/repository/PracticeRoomRepositoryTest.java
Labels: :sparkles: feature

#36 feature: 카카오 가입 response 수정 및 추가정보 구현
  src/main/java/com/umc7/ZIC/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc7/ZIC/apiPayload/exception/handler/InstrumentHandler.java
  src/main/java/com/umc7/ZIC/common/repository/InstrumentRepository.java
  src/main/java/com/umc7/ZIC/security/JwtTokenProvider.java
  src/main/java/com/umc7/ZIC/security/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/umc7/ZIC/security/SecurityConfig.java
  src/main/java/com/umc7/ZIC/user/controller/UserController.java
  src/main/java/com/umc7/ZIC/user/converter/UserConverter.java
  src/main/java/com/umc7/ZIC/user/domain/User.java
  src/main/java/com/umc7/ZIC/user/dto/UserRequestDto.java
  src/main/java/com/umc7/ZIC/user/dto/UserResponseDto.java
  src/main/java/com/umc7/ZIC/user/service/UserService.java
  src/main/java/com/umc7/ZIC/user/service/UserServiceImpl.java
  src/main/resources/templates/login.html
Labels: :hammer: refactor, :sparkles: feature

#38 feature: 엑세스 토큰 생성 테스트 api 생성
  src/main/java/com/umc7/ZIC/user/controller/UserController.java
  src/main/java/com/umc7/ZIC/user/service/UserServiceImpl.java
Labels: :sparkles: feature

#39 refactor: user, owner controller 분리
  src/main/java/com/umc7/ZIC/user/controller/OwnerController.java
  src/main/java/com/umc7/ZIC/user/controller/UserController.java
Labels: :hammer: refactor

#40 Feature: 예외 처리 추가
  src/main/java/com/umc7/ZIC/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc7/ZIC/security/CustomOAuth2UserService.java
  src/main/java/com/umc7/ZIC/user/service/UserServiceImpl.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#42 feature: 지역 처리 구현
  src/main/java/com/umc7/ZIC/common/domain/enums/RegionType.java
  src/main/java/com/umc7/ZIC/user/service/UserServiceImpl.java
Labels: :sparkles: feature

#44 feature#43-reservation-api-with-JWT
  src/main/java/com/umc7/ZIC/reservation/controller/ReservationRestController.java
  src/main/java/com/umc7/ZIC/reservation/converter/KakaoPayConverter.java
  src/main/java/com/umc7/ZIC/reservation/converter/ReservationConverter.java
  src/main/java/com/umc7/ZIC/reservation/domain/Reservation.java
  src/main/java/com/umc7/ZIC/reservation/domain/enums/Status.java
  src/main/java/com/umc7/ZIC/reservation/dto/PaymentRequestDTO.java
  src/main/java/com/umc7/ZIC/reservation/dto/ReservationRequestDTO.java
  src/main/java/com/umc7/ZIC/reservation/dto/ReservationResponseDTO.java
  src/main/java/com/umc7/ZIC/reservation/repository/ReservationRepository.java
  src/main/java/com/umc7/ZIC/reservation/service/KakaoPayService.java
  src/main/java/com/umc7/ZIC/reservation/service/KakaoPayServiceImpl.java
  src/main/java/com/umc7/ZIC/reservation/service/ReservationCommandService.java
  src/main/java/com/umc7/ZIC/reservation/service/ReservationCommandServiceImpl.java
  src/main/java/com/umc7/ZIC/reservation/service/ReservationQueryServiceImpl.java
  src/main/java/com/umc7/ZIC/security/JwtTokenProvider.java
  src/main/java/com/umc7/ZIC/user/controller/OwnerController.java
  src/main/java/com/umc7/ZIC/user/controller/UserController.java
  src/main/resources/templates/KakaoReady.html
Labels: rename, :sparkles: feature

#46 feature: security filter 설정 및 권한, jwt토큰 에러 핸들러 작성
  src/main/java/com/umc7/ZIC/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc7/ZIC/security/CustomUserDetail.java
  src/main/java/com/umc7/ZIC/security/JwtFilter.java
  src/main/java/com/umc7/ZIC/security/JwtTokenProvider.java
  src/main/java/com/umc7/ZIC/security/SecurityConfig.java
  src/main/java/com/umc7/ZIC/security/handler/CustomAccessDeniedHandler.java
  src/main/java/com/umc7/ZIC/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/umc7/ZIC/security/handler/ExceptionFilter.java
  src/main/java/com/umc7/ZIC/user/service/UserServiceImpl.java
Labels: :sparkles: feature

#49 bugfix: security 권한 필요로 인한 테스트 코드 api 위치 변경
  src/main/java/com/umc7/ZIC/common/controller/TestLoginController.java
  src/main/java/com/umc7/ZIC/user/controller/OwnerController.java
  src/main/java/com/umc7/ZIC/user/controller/UserController.java
Labels: :lady_beetle: fix

#50 bugfix: endpoint 충돌 수정
  src/main/java/com/umc7/ZIC/common/controller/TestLoginController.java
Labels: :lady_beetle: fix

#53 Feature#37 feature practice room like service controller
  src/main/java/com/umc7/ZIC/practiceRoom/controller/PracticeRoomController.java
  src/main/java/com/umc7/ZIC/practiceRoom/controller/PracticeRoomDetailController.java
  src/main/java/com/umc7/ZIC/practiceRoom/controller/PracticeRoomLikeController.java
  src/main/java/com/umc7/ZIC/practiceRoom/dto/PracticeRoomLikeRequestDto.java
  src/main/java/com/umc7/ZIC/practiceRoom/dto/PracticeRoomLikeResponseDto.java
  src/main/java/com/umc7/ZIC/practiceRoom/service/PracticeRoomDetailService.java
  src/main/java/com/umc7/ZIC/practiceRoom/service/PracticeRoomDetailServiceImpl.java
  src/main/java/com/umc7/ZIC/practiceRoom/service/PracticeRoomLikeService.java
  src/main/java/com/umc7/ZIC/practiceRoom/service/PracticeRoomLikeServiceImpl.java
  src/main/java/com/umc7/ZIC/practiceRoom/service/PracticeRoomService.java
  src/main/java/com/umc7/ZIC/practiceRoom/service/PracticeRoomServiceImpl.java
Labels: :sparkles: feature

#54 bugfix: security filter
  src/main/java/com/umc7/ZIC/config/SwaggerConfig.java
  src/main/java/com/umc7/ZIC/security/JwtFilter.java
Labels: :lady_beetle: fix

#56 feature#55 fix practiceroomdetail uri mod
  src/main/java/com/umc7/ZIC/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc7/ZIC/practiceRoom/controller/PracticeRoomDetailController.java
  src/main/java/com/umc7/ZIC/practiceRoom/repository/PracticeRoomDetailRepository.java
  src/main/java/com/umc7/ZIC/practiceRoom/service/PracticeRoomDetailService.java
  src/main/java/com/umc7/ZIC/practiceRoom/service/PracticeRoomDetailServiceImpl.java
Labels: :lady_beetle: fix, :hammer: refactor

#57 feature#52 reservation API validation 설정
  src/main/java/com/umc7/ZIC/ZicApplication.java
  src/main/java/com/umc7/ZIC/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc7/ZIC/apiPayload/exception/handler/ExceptionAdvice.java
  src/main/java/com/umc7/ZIC/apiPayload/exception/handler/ReservationHandler.java
  src/main/java/com/umc7/ZIC/common/validation/annotation/CheckPage.java
  src/main/java/com/umc7/ZIC/common/validation/validator/PageCheckValidator.java
  src/main/java/com/umc7/ZIC/practiceRoom/validation/annotation/CheckPracticeRoomDetailStatus.java
  src/main/java/com/umc7/ZIC/practiceRoom/validation/annotation/ExistPracticeRoomDetail.java
  src/main/java/com/umc7/ZIC/practiceRoom/validation/validator/PracticeRoomDetailExistValidator.java
  src/main/java/com/umc7/ZIC/practiceRoom/validation/validator/PracticeRoomDetailStatusCheckValidator.java
  src/main/java/com/umc7/ZIC/reservation/ReservationScheduler.java
  src/main/java/com/umc7/ZIC/reservation/controller/ReservationRestController.java
  src/main/java/com/umc7/ZIC/reservation/converter/ReservationConverter.java
  src/main/java/com/umc7/ZIC/reservation/domain/Reservation.java
  src/main/java/com/umc7/ZIC/reservation/domain/enums/ReservationStatus.java
  src/main/java/com/umc7/ZIC/reservation/dto/PaymentRequestDTO.java
  src/main/java/com/umc7/ZIC/reservation/dto/ReservationRequestDTO.java
  src/main/java/com/umc7/ZIC/reservation/dto/ReservationResponseDTO.java
  src/main/java/com/umc7/ZIC/reservation/repository/ReservationRepository.java
  src/main/java/com/umc7/ZIC/reservation/repository/ReservationRepositoryCustom.java
  src/main/java/com/umc7/ZIC/reservation/repository/ReservationRepositoryImpl.java
  src/main/java/com/umc7/ZIC/reservation/service/KakaoPayServiceImpl.java
  src/main/java/com/umc7/ZIC/reservation/service/ReservationCommandService.java
  src/main/java/com/umc7/ZIC/reservation/service/ReservationCommandServiceImpl.java
  src/main/java/com/umc7/ZIC/reservation/service/ReservationQueryService.java
  src/main/java/com/umc7/ZIC/reservation/service/ReservationQueryServiceImpl.java
  src/main/java/com/umc7/ZIC/reservation/validation/annotation/CheckReservationData.java
  src/main/java/com/umc7/ZIC/reservation/validation/annotation/CheckReservationStatus.java
  src/main/java/com/umc7/ZIC/reservation/validation/annotation/CheckReservationTime.java
  src/main/java/com/umc7/ZIC/reservation/validation/annotation/CheckReservationTimeOverlap.java
  src/main/java/com/umc7/ZIC/reservation/validation/annotation/ExistReservation.java
  src/main/java/com/umc7/ZIC/reservation/validation/validationSequence/ValidationOrder.java
  src/main/java/com/umc7/ZIC/reservation/validation/validationSequence/ValidationStep.java
  src/main/java/com/umc7/ZIC/reservation/validation/validator/ReservationDataCheckValidator.java
  src/main/java/com/umc7/ZIC/reservation/validation/validator/ReservationExistValidator.java
  src/main/java/com/umc7/ZIC/reservation/validation/validator/ReservationStatusCheckValidator.java
  src/main/java/com/umc7/ZIC/reservation/validation/validator/ReservationTimeCheckValidator.java
  src/main/java/com/umc7/ZIC/reservation/validation/validator/ReservationTimeOverlapCheckValidator.java
  src/main/java/com/umc7/ZIC/user/controller/OwnerController.java
  src/main/java/com/umc7/ZIC/user/repository/UserRepositoryImpl.java
Labels: comment, rename, remove, :sparkles: feature
